### ISSUE TITLE
New official Dracula theme

### ISSUE THREAD

**Issue by SlyBouhafs** [jonhadfield/awesome-standard-notes#16]
Hey!

I made a new (official) Dracula theme for SN: https://github.com/dracula/sn-theme-dracula
Can you add it to the awesome list?

I am waiting for the other theme creators to join efforts so we can all work on the same theme.

**Comment by jonhadfield** [comment]
Sure. I'll pick this up.

**Comment by jonhadfield** [comment]
Done.
I copied the description from your GitHub page. Please shout if you want it amended.
