### ISSUE TITLE
Using the name "Outline" to promote the Rich Markdown Editor may be a violation of their BSD-3 License

### ISSUE THREAD

**Issue by TheodoreChu** [jonhadfield/awesome-standard-notes#17]
The 3rd clause in the BSD-3 Licensed used by the [Rich Markdown Editor](https://github.com/outline/rich-markdown-editor) states this:

> 3. Neither the name of the Outline nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

Source: https://github.com/outline/rich-markdown-editor/blob/develop/LICENSE#L11-L12

As a result, naming Outline in the [Editors section](https://github.com/jonhadfield/awesome-standard-notes/blob/master/README.md#editors) to promote the @arturolinares 's sn-rme may be a violation of their license. I'm not sure if @arturolinares has received written permission to use the name "Outline" to promote sn-rme, but this is something to be aware of.

**Comment by arturolinares** [comment]
The intention is not to _promote or endorse a product_, but to give due attribution. 

I'm concerned that if I remove the "Outline" mention people might think I implemented the editor. In the other hand, I'm not an English native speaker and maybe the language could be adjusted to make the attribution evident without violating the BSD-3 license.

**Comment by jrabensc** [comment]
I agree with @arturolinares. @TheodoreChu, do you have any idea how we could describe the editor? I'm not a native speaker as well.

**Comment by TheodoreChu** [comment]
OK, that makes sense; attribution is good. I think we can give attribution without mentioning Outline by referencing the GitHub repository of the Rich Markdown Editor: https://github.com/outline/rich-markdown-editor

I recently added the Rich Markdown Editor to the Append Editor and I wanted to make sure that I was following the BSD-3 License properly, so I asked the developer, @tommoor, about how to follow it. Tom responded that I should link to the GitHub repository, use the term "Rich Markdown Editor", but ideally not use "by Outline" or "Outline".

This is what I have in the [README.md](https://github.com/theodorechu/append-editor#features) for the Append Editor. Tom told me that it works fine:
> Optional dynamic, what-you-see-is-what-you-get live formatting provided by the [Rich Markdown Editor](https://github.com/outline/rich-markdown-editor). 

In this Awesome list, we currently have something like this:
> [Rich Markdown Editor](https://github.com/arturolinares/sn-rme) - The awesome editor developed by [Outline](https://www.getoutline.com/). Supports tables, YouTube embeds and text highlights.

I suggest that we have something like this:
> [Rich Markdown Editor](https://github.com/arturolinares/sn-rme) - An awesome WYSIWYG markdown editor provided by the [Rich Markdown Editor](https://github.com/outline/rich-markdown-editor) that supports tables, YouTube embeds, and text highlights.

How does that sound? Of course, you can further edit it to suit your liking, but I think that's one way in which we can provide appropriate attribution without mentioning Outline.

**Comment by tommoor** [comment]
Hey folks, thank you for raising this issue and taking the time to consider the licensing seriously.

In terms of this list, I think "developed by Outline" is okay – the purpose of the license clause is to ensure that other projects don't use the "Outline" project's name and branding in their marketing materials and cause undue confusion. The wording you have here is clear and the link back to the Outline site is appreciated. @TheodoreChu you may use the same language if you prefer or stick with what you have.

**Consider this written permission.**

**Comment by TheodoreChu** [comment]
Sounds great. Thank you, @tommoor! 😄

I'll go ahead and close the issue since Tom's comment seems to have settled it.
