### ISSUE TITLE
Add Fast editor

### ISSUE THREAD

**Issue by dec0dOS** [jonhadfield/awesome-standard-notes#25]
Hello! Thanks for your contributions! This repo is a great starting point for the SN community.

Please add my editor to the list:

`* [Fast Editor](https://github.com/dec0dOS/standard-notes-fast-editor) - A markdown mobile-friendly and high-performance editor with clickable links on mobile and desktop.
`

**Comment by jonhadfield** [comment]
Thanks @dec0dOS
This has been added.
