### ISSUE TITLE
Suggestion: Remove or annotate "Standard Notes Clipper"

### ISSUE THREAD

**Issue by Marxsal** [jonhadfield/awesome-standard-notes#33]
The Standard Notes Clipper appears to have been broken since library changes in SN in Jan 21. IMO it should be either removed or annotated with a warning.

**Comment by jonhadfield** [comment]
Thanks for the heads up.  
I've pinged the developer on the Standard Notes slack channel #clipper-beta-testers. I'll stick a warning next to it in the meantime, with a link to the [issue](https://github.com/johnjones4/Standard-Notes-Clipper/issues/34) you raised.
