### ISSUE TITLE
Add Standard Notes Flatpak

### ISSUE THREAD

**Issue by proletarius101** [jonhadfield/awesome-standard-notes#36]
Since the appimage is mentioned, it would be nice to mention the flatpak as well, which is more integrated into the Linux desktop environment

https://flathub.org/apps/details/org.standardnotes.standardnotes

**Comment by jrabensc** [comment]
Is this an official image @JaspalSuri ?

**Comment by proletarius101** [comment]
> Is this an official image @JaspalSuri ?

It's built directly from the code. But it's not maintained by the SN company. Otherwise it should be just listed in the official website.

**Comment by jrabensc** [comment]
4eaf27fdc4ec3d9477dcf7c438834ca48ac942b
