### ISSUE TITLE
Standard Notes Writer is a theme not a editor

### ISSUE THREAD

**Issue by DanielNetoP** [jonhadfield/awesome-standard-notes#52]
Hi, I was going through all items and just realized that `[Standard Notes Writer](https://github.com/eenpadvinder/standardnotes-writer) - Distraction free writing with word count` is not a editor but a theme, it's in the wrong section

**Comment by jrabensc** [comment]
Could you please create a PR?

**Comment by DanielNetoP** [comment]
Done 👍
