### ISSUE TITLE
Error message:    err: cache item is missing 

### ISSUE THREAD

**Issue by benjaloo** [jonhadfield/awesome-standard-notes#54]
Hi! Love the idea of CLI client for Standard Notes, but won't work for me. I installed v0.2.4 , it ran but when I tried to get notes using either title, text or UUID, I got this error message 

err: cache item is missing items_key_id: 

followed by what looked like the note in JSON, encrypted.

I downloaded and tried v0.2.2, same result. (v0.2.3 was flagged by my antivirus)

**Comment by jonhadfield** [comment]
Hi @benjaloo, there seems to have been an update to the Standard Notes API that's not compatible with my app. I'll create an issue in the repo github.com/jonhadfield/sn-cli to track.  
Regarding the antivirus false-positive, this is common for go binaries and also unavoidable.: https://github.com/jonhadfield/soba/issues/8
