### ISSUE TITLE
add theme uniform-dark-theme-sn

### ISSUE THREAD

**Issue by John3** [jonhadfield/awesome-standard-notes#6]
hi again 👍 

That was quick 😄 thanks

uniform-dark-theme-sn: https://gitlab.com/dark-themes/uniform-dark-theme-sn

**Comment by jrabensc** [comment]
yw.

https://github.com/jonhadfield/awesome-standard-notes/commit/4de7b3c64fc1e58a3a946cd1624ea6f945299e4d
