### ISSUE TITLE
Tangerine 

### ISSUE THREAD

**Issue by shompoe** [jonhadfield/awesome-standard-notes#60]
Hi,

Sorry but I don't know how to make a PR.

I have finally gotten my theme to work correctly again after SN was updated a long time ago. Then after pulling my hair out for an entire day I discovered that it seems the only way to make the mobile app update to the latest version of the theme is to rename the repository. 

Could you update the URL for tangerine to this: https://github.com/shompoe/sn-orange

Thanks

**Comment by jonhadfield** [comment]
Updated.

Thanks
