### ISSUE TITLE
some broken links / confusing links

### ISSUE THREAD

**Issue by erexer** [jonhadfield/awesome-standard-notes#73]
- first `[Dracula theme](https://github.com/cameronldn/sn-theme-dracula)` link is broken
- some themes link to the install link rather than the github repo, it'd be nice if all the links were standardized for either the install or for the repo (happens for Monochrome Dark Theme, Subtle Dark Theme, Subtle Light Theme, maybe others)

**Comment by jonhadfield** [comment]
Thanks for reporting @erexer and sorry for the delay.   
I've fixed the broken links and removed the 'now missing' themes. Will see what I can do to standardise when I get a minute.
